rocketmq:
  name-server: localhost:9876
  producer:
    group: orderProducerGroup
server:
  port: 8181

mq:
  order:
    consumer:
      group:
        name: order_orderTopic_cancel_group
    topic: orderTopic
    tag:
      confirm: order_confirm
      cancel: order_cancel


spring:
  application:
    name: example-shop
  datasource:
    username: root
    password: Chen123@@@
    url: jdbc:mysql://localhost:3306/rocketmq-example?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&AllowPublicKeyRetrieval=True
    driver-class-name=com: com.mysql.jdbc.Driver

mybatis-plus:
  mapper-locations: mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  type-aliases-package: com.example.domain.po

example:
  name: 商品服务
